### ISSUE TITLE
Error: Cannot find module 'del'

### ISSUE THREAD

**Issue by elartix** [sajera/generator-electron-angular#1]
```
Elartix\test-ng-electron>yo electron-angular
module.js:471
    throw err;
    ^

Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Elartix\AppData\Roaming\npm\node_modules\generator-electron-angular\generators\app\util.js:7:11
)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by sajera** [comment]
Sorry, my bad.
To the evening all corrected. With the 0.9.1 update.
